# CREATE STORE
dstore create flow-system-totorial

# ACTIVATE
active flow-system-totorial

# SET OUTPUT TO PRINT DIRECTLY TO CONSOLE
set output out

# DEFINE PREFIXES
prefix fso: <https://w3id.org/fso#>
prefix ex: <https://example.com/ex#>

# LOAD ABOX
import "./fso-abox.ttl"
import "./boundary-conditions.ttl"
import "./fluids.ttl"

# LOAD TBOX
import > <https://w3id.org/fso> "./fso.ttl"
importaxioms <https://w3id.org/fso>

# LOAD RULES
import "./RULES/terminal-temperature-difference.dlog"
import "./RULES/terminal-flow-simple.dlog"

# RUN TEST QUERY
SELECT ?t ?q WHERE { \
    ?t a fso:Terminal ; \
        ex:terminalVolumeFlow ?q . \
}

# REMOVE STORE
dstore delete flow-system-totorial force

# QUIT
quit